### ISSUE TITLE
Deal with images in different formats

### ISSUE THREAD

**Issue by henare** [openaustralia/australian_local_councillors_images#2]
I've just seen an image as a GIF! http://www.bmcc.nsw.gov.au/files/MGreenhill.gif

**Comment by equivalentideas** [comment]
This can be handled by the [image-proxy](https://github.com/jpmckinney/image-proxy) we're looking to use for resizing ( #5 ). However there is currently [a bug in it’s transcoding behaviour](https://github.com/jpmckinney/image-proxy/issues/21).

I've submitted [a PR to fix it](https://github.com/jpmckinney/image-proxy/pull/22).

**Comment by equivalentideas** [comment]
Since https://github.com/openaustralia/australian_local_councillors_images/compare/48935fa7717b...69c965bda286 our [image proxy](https://github.com/openaustralia/image-proxy/tree/update_buildpacks_and_convert_image) is now reformatting all images to JPEGs for us. See example:

![](http://floating-refuge-38180.herokuapp.com/http%3A%2F%2Fwww.bmcc.nsw.gov.au%2Ffiles%2FMGreenhill.gif/80/88.jpg)

Generated from:

![](http://www.bmcc.nsw.gov.au/files/MGreenhill.gif)
